### ISSUE TITLE
Regex bug is replacing hypens in project names with underscores

### ISSUE THREAD

**Issue by nosami** [intellifactory/websharper.templates#3]
See [here](https://bugzilla.xamarin.com/show_bug.cgi?id=34096) for background

 https://github.com/intellifactory/websharper.templates/blob/master/WebSharper.Templates/Templates.fs#L44-L55 :-

You have a bug in your regex here

```fs
open System.Text.RegularExpressions
let str = "test-project.fsproj"
let UnsafeChars =
        Regex("[^_0-9a-zA-Z.]")
UnsafeChars.Replace(str, "_")
```
output
```
val str : string = "test-project.fsproj"
val UnsafeChars : System.Text.RegularExpressions.Regex = [^_0-9a-zA-Z.]
val it : string = "test_project.fsproj"
```

**Comment by nosami** [comment]
It should probably allow hyphens when running on linux or OSX

**Comment by Tarmil** [comment]
The issue is slightly more complex because `ProjectName` is also used for text replacement inside files (namespaces, assembly name), where it should not contain dashes. Basically we need two separate `ProjectName`s, one for the project file name and one for inside files. I'm on it.

**Comment by nosami** [comment]
Thanks!
