### ISSUE TITLE
VS2015/VS2017 support

### ISSUE THREAD

**Issue by Jand42** [intellifactory/websharper.templates#8]
Clean install of VS2017 does not guarantee F# 4.0 availability. VS2015 only supports F# 4.0.

Currently (as of beta10): two branches are producing separate installers:
`master` for VS2017
`vs2015` for VS2015

Also, some C# templates use C# 7.0 shorthand in the VS2017 version.

**Comment by granicz** [comment]
I don't think we should have a separate branch nor a separate installer for VS 2015. We can add instructions to the various template files that need adjustment, and keep a single installer.

**Comment by Jand42** [comment]
No need for instructions now, a custom wizard (running without UI) sets `$visualstudioversion$` and `$fsharpcoreversion$` parameters to allow multi-targeting.
